packages:
  - 'apps/*'
  - 'packages/*'
  - 'examples/*'

catalog:
  hono: ^4.11.3
  graphql: 16.12.0
  graphql-yoga: ^5.18.0
  zod: ^4.0.0
  capnweb: ^0.4.0
  '@hono/capnweb': ^0.1.0
  '@hono/node-server': ^1.19.7
  '@hono/node-ws': ^1.3.0
  commander: ^14.0.2
  '@graphql-tools/schema': ^10.0.31
  '@graphql-tools/delegate': ^12.0.4
  '@graphql-tools/stitch': ^10.1.8
  '@graphql-tools/utils': ^11.0.0
  '@graphql-tools/wrap': ^11.1.4
  '@graphql-tools/stitching-directives': ^4.0.10
  '@aws-sdk/client-s3': ^3.964.0
  jose: ^6.0.0
  argon2: ^0.44.0
  better-sqlite3: ^12.6.2
  '@cedar-policy/cedar-wasm': ^4.8.2
  '@opentelemetry/api': ^1.9.0
  chalk: ^5.3.0
  inquirer: ^9.2.14
  ws: ^8.19.0
  ip: ^2.0.1

catalogs:
  dev:
    esbuild: ^0.25.0
    typescript: ^5.9.3
    '@types/node': ^25.0.3
    '@types/better-sqlite3': ^7.6.13
    tsup: ^8.5.1
    tsx: ^4.7.1
    '@types/inquirer': ^9.0.7
    '@types/ws': ^8.18.1
  testing:
    vitest: ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    testcontainers: ^11.11.0
    '@playwright/test': ^1.57.0
