import type { VideoConfig } from '@catalyst/config'

export function generateMediaMTXConfig(config: VideoConfig, servicePort: number): string {
  return `# Auto-generated by VideoService — do not edit
api: true
apiAddress: :9997

rtsp: true
rtspAddress: :${config.rtspPort}

srt: true
srtAddress: :${config.srtPort}

hls: true
hlsAddress: :${config.hlsPort}

webrtc: true
webrtcAddress: :${config.webrtcPort}

authInternalUsers: []
authHTTPAddress: http://localhost:${servicePort}/video-stream/auth

pathDefaults:
  authFailOnPublish: ${config.authFailPublish}
  authFailOnRead: ${config.authFailSubscribe}
  publishIPs:
    - 127.0.0.1
    - "::1"
  runOnReady: curl -s -X POST -H "Content-Type: application/json" -d '{"path":"$MTX_PATH","sourceType":"$MTX_SOURCE_TYPE"}' http://localhost:${servicePort}/video-stream/hooks/ready
  runOnNotReady: curl -s -X POST -H "Content-Type: application/json" -d '{"path":"$MTX_PATH"}' http://localhost:${servicePort}/video-stream/hooks/not-ready
`
}
