#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RPI_IMAGE_GEN=""
BUILD_DIR=""
SOURCE_DIR=""
SKIP_DEPS=false
CLONE_BRANCH="master"
CONFIG_FILE=""

# ---------- Usage ----------

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS] <config.yaml>

Build a Raspberry Pi image from an rpi-image-gen config YAML.

This script handles the full pipeline:
  1. Clones rpi-image-gen if not already present
  2. Installs system dependencies (requires sudo, one-time)
  3. Runs the image build (no root needed)
  4. Prints flash instructions

The config YAML is typically generated by the catalyst-rpi-config CLI:
  bun run apps/rpi-config/src/index.ts --non-interactive --password p --peering-secret s

Arguments:
  <config.yaml>                Path to the rpi-image-gen config YAML

Options:
  --source-dir <path>          Source directory for rpi-image-gen -S flag.
                               Use the output directory from catalyst-rpi-config.
                               (default: builds/rpi/ next to this script)
  --rpi-image-gen <path>       Path to existing rpi-image-gen checkout
                               (default: clone to ./rpi-image-gen next to this script)
  --build-dir <path>           Build output directory (passed as -B to rpi-image-gen)
  --skip-deps                  Skip dependency installation
  --branch <branch>            Git branch to clone (default: master)
  -h, --help                   Show this help

Requirements:
  - Debian Bookworm or Trixie arm64 host (Pi 5 with Pi OS recommended)
  - sudo access for one-time dependency installation
  - ~4GB free disk space for a minimal image build

Not on Linux? Use the Docker-based builder instead:
  ./builds/rpi/build-docker.sh --source-dir dist/rpi dist/rpi/config.yaml

Examples:
  # Generate config with the CLI, then build from output dir
  bun run apps/rpi-config/src/index.ts --non-interactive --password p --peering-secret s
  ./builds/rpi/build.sh --source-dir dist/rpi dist/rpi/config.yaml

  # Use an existing rpi-image-gen checkout
  ./builds/rpi/build.sh --rpi-image-gen ~/rpi-image-gen --source-dir dist/rpi dist/rpi/config.yaml

  # Skip deps if already installed
  ./builds/rpi/build.sh --skip-deps --source-dir dist/rpi dist/rpi/config.yaml

  # Legacy: use builds/rpi/ as source dir (default when --source-dir omitted)
  ./builds/rpi/build.sh /path/to/config.yaml

EOF
  exit 0
}

# ---------- Argument parsing ----------

while [[ $# -gt 0 ]]; do
  case $1 in
    --source-dir)     SOURCE_DIR="$2"; shift 2;;
    --rpi-image-gen)  RPI_IMAGE_GEN="$2"; shift 2;;
    --build-dir)      BUILD_DIR="$2"; shift 2;;
    --skip-deps)      SKIP_DEPS=true; shift;;
    --branch)         CLONE_BRANCH="$2"; shift 2;;
    -h|--help)        usage;;
    -*)               echo "Unknown option: $1"; echo ""; usage;;
    *)
      if [[ -z "$CONFIG_FILE" ]]; then
        CONFIG_FILE="$1"; shift
      else
        echo "ERROR: Unexpected argument: $1"
        echo "Only one config file can be specified."
        exit 1
      fi
      ;;
  esac
done

if [[ -z "$CONFIG_FILE" ]]; then
  echo "ERROR: No config YAML specified."
  echo ""
  usage
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: Config file not found: $CONFIG_FILE"
  exit 1
fi

CONFIG_FILE="$(cd "$(dirname "$CONFIG_FILE")" && pwd)/$(basename "$CONFIG_FILE")"

# ---------- Host checks ----------

check_host() {
  echo "=== Host Environment ==="

  local os
  os="$(uname -s)"

  # Non-Linux hosts cannot run rpi-image-gen natively
  if [[ "$os" != "Linux" ]]; then
    echo "ERROR: This script requires a Linux host (detected: $os)."
    echo ""
    echo "  On macOS/Windows, use the Docker-based builder instead:"
    echo ""

    # Reconstruct the equivalent build-docker.sh command
    local docker_cmd="${SCRIPT_DIR}/build-docker.sh"
    [[ -n "$SOURCE_DIR" ]] && docker_cmd+=" --source-dir ${SOURCE_DIR}"
    [[ -n "$BUILD_DIR" ]]  && docker_cmd+=" --build-dir ${BUILD_DIR}"
    docker_cmd+=" ${CONFIG_FILE}"
    echo "    $docker_cmd"
    echo ""
    echo "  This runs the build inside a Debian arm64 container with all"
    echo "  dependencies pre-installed. Requires Docker Desktop."
    echo ""
    exit 1
  fi

  # Check architecture
  local arch
  arch="$(uname -m)"
  if [[ "$arch" != "aarch64" ]]; then
    echo "WARNING: Host architecture is $arch, not aarch64."
    echo "  rpi-image-gen is supported on Debian arm64 hosts only."
    echo "  The build may fail or produce incorrect images."
    echo ""
    read -rp "Continue anyway? [y/N]: " confirm
    if [[ ! "${confirm:-n}" =~ ^[Yy] ]]; then
      echo "Aborted."
      exit 0
    fi
  fi

  # Check OS
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    source /etc/os-release
    echo "  OS:   ${PRETTY_NAME:-unknown}"
  fi
  echo "  Arch: $arch"
  echo ""
}

# ---------- Clone rpi-image-gen ----------

ensure_rpi_image_gen() {
  if [[ -n "$RPI_IMAGE_GEN" ]]; then
    if [[ ! -d "$RPI_IMAGE_GEN" ]]; then
      echo "ERROR: --rpi-image-gen path does not exist: $RPI_IMAGE_GEN"
      exit 1
    fi
    RPI_IMAGE_GEN="$(cd "$RPI_IMAGE_GEN" && pwd)"
    echo "Using existing rpi-image-gen: $RPI_IMAGE_GEN"
    return
  fi

  # Default location: next to this script's parent (builds/)
  RPI_IMAGE_GEN="${SCRIPT_DIR}/rpi-image-gen"

  if [[ -d "$RPI_IMAGE_GEN" ]]; then
    echo "Found rpi-image-gen at $RPI_IMAGE_GEN"
    echo "Pulling latest changes..."
    git -C "$RPI_IMAGE_GEN" pull --ff-only 2>/dev/null || true
    return
  fi

  echo "=== Cloning rpi-image-gen ==="
  echo "  Target: $RPI_IMAGE_GEN"
  echo "  Branch: $CLONE_BRANCH"
  echo ""

  git clone --depth 1 --branch "$CLONE_BRANCH" \
    https://github.com/raspberrypi/rpi-image-gen.git \
    "$RPI_IMAGE_GEN"

  echo ""
  echo "Cloned rpi-image-gen to $RPI_IMAGE_GEN"
}

# ---------- Install dependencies ----------

install_deps() {
  if [[ "$SKIP_DEPS" == true ]]; then
    echo "Skipping dependency installation (--skip-deps)"
    return
  fi

  local install_script="${RPI_IMAGE_GEN}/install_deps.sh"

  if [[ ! -f "$install_script" ]]; then
    echo "WARNING: install_deps.sh not found at $install_script"
    echo "  Dependencies may not be installed. Use --skip-deps to silence this."
    return
  fi

  # Check if deps are likely already installed by looking for key binaries
  local missing=false
  for cmd in mmdebstrap podman genimage; do
    if ! command -v "$cmd" &>/dev/null; then
      missing=true
      break
    fi
  done

  if [[ "$missing" == false ]]; then
    echo "Dependencies appear to be installed (mmdebstrap, podman, genimage found)"
    return
  fi

  echo "=== Installing Dependencies ==="
  echo "  This requires sudo and only needs to run once per host."
  echo ""

  # Run from the
  pushd "$RPI_IMAGE_GEN"
  sudo ./install_deps.sh
  popd

  echo ""
  echo "Dependencies installed."
}

# ---------- Validate config ----------

validate_config() {
  echo "=== Validating Config ==="
  echo "  Config: $CONFIG_FILE"

  # Basic YAML structure check — ensure it has the required top-level keys
  if ! python3 -c "
import yaml, sys
with open(sys.argv[1]) as f:
    cfg = yaml.safe_load(f)
required = ['include', 'device', 'image', 'layer']
missing = [k for k in required if k not in cfg]
if missing:
    print(f'ERROR: Missing required sections: {missing}', file=sys.stderr)
    sys.exit(1)
print(f'  Sections: {list(cfg.keys())}')
print(f'  Device:   {cfg[\"device\"].get(\"layer\", \"unknown\")}')
print(f'  Image:    {cfg[\"image\"].get(\"name\", \"unknown\")}')
layers = cfg.get('layer', {})
print(f'  Layers:   {list(layers.values())}')
" "$CONFIG_FILE" 2>&1; then
    echo ""
    echo "ERROR: Config validation failed."
    exit 1
  fi

  echo "  Valid."
  echo ""
}

# ---------- Build ----------

run_build() {
  # Resolve source directory: --source-dir takes priority, else fall back to SCRIPT_DIR
  local src_dir="${SOURCE_DIR:-$SCRIPT_DIR}"
  if [[ -n "$SOURCE_DIR" ]]; then
    src_dir="$(cd "$SOURCE_DIR" && pwd)"
  fi

  echo "=== Building Image ==="
  echo "  rpi-image-gen: $RPI_IMAGE_GEN"
  echo "  Source dir:    $src_dir"
  echo "  Config:        $CONFIG_FILE"
  if [[ -n "$BUILD_DIR" ]]; then
    echo "  Build dir:     $BUILD_DIR"
  fi
  echo ""

  local build_args=()
  build_args+=("-S" "$src_dir")
  build_args+=("-c" "$CONFIG_FILE")

  if [[ -n "$BUILD_DIR" ]]; then
    build_args+=("-B" "$BUILD_DIR")
  fi

  "${RPI_IMAGE_GEN}/rpi-image-gen" build "${build_args[@]}"
}

# ---------- Post-build ----------

print_results() {
  local work_dir="${BUILD_DIR:-${RPI_IMAGE_GEN}/work}"

  # Try to find the output image
  local image_name
  image_name="$(python3 -c "
import yaml, sys
with open(sys.argv[1]) as f:
    cfg = yaml.safe_load(f)
print(cfg.get('image', {}).get('name', 'unknown'))
" "$CONFIG_FILE" 2>/dev/null || echo "unknown")"

  local image_dir="${work_dir}/image-${image_name}"
  local image_file="${image_dir}/${image_name}.img"

  echo ""
  echo "=== Build Complete ==="
  echo ""

  if [[ -f "$image_file" ]]; then
    local size
    size="$(du -h "$image_file" | cut -f1)"
    echo "  Image: $image_file ($size)"
  else
    echo "  Image directory: $image_dir"
    echo "  (Check above for the exact output path)"
  fi

  echo ""
  echo "  To flash to an SD card:"
  echo ""
  echo "    sudo rpi-imager --cli ${image_file} /dev/mmcblk0"
  echo ""
  echo "  Or use Raspberry Pi Imager (GUI) and select the .img file."
  echo ""
}

# ---------- Main ----------

main() {
  echo ""
  echo "  Catalyst Node — RPi Image Builder"
  echo ""

  check_host
  ensure_rpi_image_gen
  install_deps
  validate_config
  run_build
  print_results
}

main
